package:
  name: clblast
  version: 1.6.3
  epoch: 2
  description: Tuned OpenCL BLAS
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - opencl-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/CNugteren/CLBlast
      tag: ${{package.version}}
      expected-commit: 2a081972b20911ddf76a6b40df717c7d0c181268

  - uses: cmake/configure

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: ${{package.name}}-dev
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/pkgconf

update:
  enabled: true
  github:
    identifier: CNugteren/CLBlast
