package:
  name: libtbb
  version: "2022.1.0"
  epoch: 1
  description: "oneAPI Threading Building Blocks"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - samurai
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/oneapi-src/oneTBB
      tag: v${{package.version}}
      expected-commit: 45587e94dfb6dfe00220c5f520020a5bc745e92f

  - name: 'Set version and types'
    runs: |
      sed -e "s@#define MALLOC_UNIXLIKE_OVERLOAD_ENABLED __linux__@@"  -i src/tbbmalloc_proxy/proxy.h

  - name: 'Configure libtbb'
    runs: |
      CFLAGS="$CFLAGS -flto=auto" \
      CXXFLAGS="$CXXFLAGS -flto=auto" \
      cmake -B build -G Ninja \
       -DCMAKE_C_COMPILER=gcc \
       -DCMAKE_CXX_COMPILER=g++ \
       -DCMAKE_BUILD_TYPE=MinSizeRel \
       -DCMAKE_INSTALL_PREFIX=/usr \
       -DCMAKE_INSTALL_LIBDIR=lib \
       -DTBB4PY_BUILD=OFF \
       -DTBB_STRICT=OFF \
       -DTBB_TEST=OFF

  - runs: |
      cmake --build build

  - runs: |
      DESTDIR="${{targets.destdir}}" cmake --install build

subpackages:
  - name: "libtbb-dev"
    description: "headers for libtbb"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libtbb
    test:
      pipeline:
        - uses: test/pkgconf
        - uses: test/tw/ldd-check

  - name: libtbb-doc
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share/doc/TBB
          mv "${{targets.destdir}}"/usr/share/doc/TBB/README.md "${{targets.subpkgdir}}"/usr/share/doc/TBB/README.md
    description: libtbb readme
    test:
      pipeline:
        - uses: test/docs

update:
  enabled: true
  github:
    identifier: oneapi-src/oneTBB
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - gcc
        - glibc-dev
        - libtbb-dev
  pipeline:
    - name: Compile and run basic threading test
      runs: |
        echo '#include <tbb/tbb.h>
        #include <iostream>
        int main() {
            tbb::parallel_for(0, 10, [](int i) { std::cout << i << " "; });
            std::cout << std::endl;
            return 0;
        }' > threading_test.cpp
        g++ threading_test.cpp -o threading_test -ltbb
        ./threading_test
    - uses: test/tw/ldd-check
